#!/bin/bash
# Idempotent Coder bootstrap: first user + seam-agent template + API token.
# Runs as the coder-init docker compose service on every `docker compose --profile coder up`.
# Safe to re-run — skips steps that are already done.
set -euo pipefail

CODER_URL="${CODER_INTERNAL_URL:-http://coder:7080}"
CODER_EXTERNAL_URL="${CODER_EXTERNAL_URL:-http://localhost:7080}"
CODER_FIRST_USER_EMAIL="${CODER_FIRST_USER_EMAIL:-admin@seam.local}"
CODER_FIRST_USER_USERNAME="${CODER_FIRST_USER_USERNAME:-seam-admin}"
CODER_FIRST_USER_PASSWORD="${CODER_FIRST_USER_PASSWORD:-seamadmin123}"
CODER_FIRST_USER_TRIAL="${CODER_FIRST_USER_TRIAL:-false}"
TOKEN_NAME="seam-integration"
OUTPUT_DIR="${OUTPUT_DIR:-/output}"

# --- install jq if missing ---

if ! command -v jq &> /dev/null; then
  echo "Installing jq..."
  if command -v apk &> /dev/null; then
    apk add --no-cache jq > /dev/null 2>&1
  elif command -v apt-get &> /dev/null; then
    apt-get update -qq && apt-get install -y -qq jq > /dev/null 2>&1
  else
    # Download static binary as fallback
    curl -sfL -o /usr/local/bin/jq https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64
    chmod +x /usr/local/bin/jq
  fi
fi

# --- wait for coder API ---

echo "Waiting for Coder API at $CODER_URL ..."
for i in $(seq 1 60); do
  if curl -sf "$CODER_URL/api/v2/buildinfo" > /dev/null 2>&1; then
    break
  fi
  if [ "$i" -eq 60 ]; then
    echo "ERROR: Coder API not reachable after 120s"
    exit 1
  fi
  sleep 2
done
echo "Coder API ready"

# --- create first user (or login if exists) ---

SESSION_TOKEN=""

HTTP_CODE=$(curl -s -w "%{http_code}" -o /tmp/first-user.json \
  -X POST "$CODER_URL/api/v2/users/first" \
  -H "Content-Type: application/json" \
  -d "{
    \"email\": \"$CODER_FIRST_USER_EMAIL\",
    \"username\": \"$CODER_FIRST_USER_USERNAME\",
    \"password\": \"$CODER_FIRST_USER_PASSWORD\",
    \"trial\": $CODER_FIRST_USER_TRIAL
  }")

if [ "$HTTP_CODE" = "201" ]; then
  echo "First user created: $CODER_FIRST_USER_USERNAME"
  SESSION_TOKEN=$(jq -r '.session_token' /tmp/first-user.json)
else
  # User already exists — login instead
  HTTP_CODE=$(curl -s -w "%{http_code}" -o /tmp/login.json \
    -X POST "$CODER_URL/api/v2/users/login" \
    -H "Content-Type: application/json" \
    -d "{
      \"email\": \"$CODER_FIRST_USER_EMAIL\",
      \"password\": \"$CODER_FIRST_USER_PASSWORD\"
    }")

  if [ "$HTTP_CODE" = "201" ]; then
    echo "Logged in as: $CODER_FIRST_USER_USERNAME"
    SESSION_TOKEN=$(jq -r '.session_token' /tmp/login.json)
  else
    echo "ERROR: Could not create or login first user (HTTP $HTTP_CODE)"
    cat /tmp/first-user.json 2>/dev/null || true
    cat /tmp/login.json 2>/dev/null || true
    exit 1
  fi
fi

if [ -z "$SESSION_TOKEN" ]; then
  echo "ERROR: No session token obtained"
  exit 1
fi

AUTH_HEADER="Coder-Session-Token: $SESSION_TOKEN"

# --- push seam-agent template (if not exists) ---

TEMPLATE_CHECK=$(curl -s -o /dev/null -w "%{http_code}" \
  -H "$AUTH_HEADER" \
  "$CODER_URL/api/v2/organizations/default/templates/seam-agent")

if [ "$TEMPLATE_CHECK" = "200" ]; then
  echo "Template 'seam-agent' already exists — skipping push"
else
  echo "Pushing seam-agent template..."
  # Configure CLI to talk to the internal Coder URL
  export CODER_URL="$CODER_URL"
  export CODER_SESSION_TOKEN="$SESSION_TOKEN"

  coder templates push seam-agent \
    --directory /templates/seam-agent \
    --yes 2>&1 || {
      echo "ERROR: Template push failed"
      exit 1
    }
  echo "Template 'seam-agent' pushed"
fi

# Record template hash so host-side sync can detect changes
TEMPLATE_HASH=$(find /templates/seam-agent -type f -print0 | sort -z | xargs -0 sha256sum | sha256sum | cut -d' ' -f1)
echo "$TEMPLATE_HASH" > "$OUTPUT_DIR/.coder-template-hash"
echo "Template hash recorded: ${TEMPLATE_HASH:0:12}…"

# --- create API token for seam server ---

# Delete existing token with same name (idempotent refresh)
EXISTING_TOKENS=$(curl -sf -H "$AUTH_HEADER" \
  "$CODER_URL/api/v2/users/me/keys/tokens" 2>/dev/null || echo "[]")

# Check if our token name exists and delete it
EXISTING_ID=$(echo "$EXISTING_TOKENS" | jq -r ".[] | select(.token_name == \"$TOKEN_NAME\") | .id" 2>/dev/null | head -1 || true)

if [ -n "$EXISTING_ID" ]; then
  curl -sf -X DELETE -H "$AUTH_HEADER" \
    "$CODER_URL/api/v2/users/me/keys/$EXISTING_ID" > /dev/null 2>&1 || true
  echo "Deleted existing '$TOKEN_NAME' token"
fi

# Create fresh token (30-day lifetime in nanoseconds)
TOKEN_RESULT=$(curl -sf -X POST \
  -H "$AUTH_HEADER" \
  -H "Content-Type: application/json" \
  "$CODER_URL/api/v2/users/me/keys/tokens" \
  -d "{\"name\": \"$TOKEN_NAME\", \"lifetime\": 2592000000000000}")

API_TOKEN=$(echo "$TOKEN_RESULT" | jq -r '.key')

if [ -z "$API_TOKEN" ]; then
  echo "ERROR: Failed to create API token"
  echo "$TOKEN_RESULT"
  exit 1
fi

# --- write env file for seam server ---

cat > "$OUTPUT_DIR/.env.coder" <<EOF
# Auto-generated by coder-init. Do not edit — will be overwritten on next startup.
CODER_URL=$CODER_EXTERNAL_URL
CODER_TOKEN=$API_TOKEN
EOF

echo ""
echo "=== Coder bootstrap complete ==="
echo "  User:     $CODER_FIRST_USER_USERNAME ($CODER_FIRST_USER_EMAIL)"
echo "  Template: seam-agent"
echo "  Token:    written to .env.coder"
echo "  URL:      $CODER_EXTERNAL_URL"
